core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import (
    home, product_page, add_cart, cart_detail, cart_remove, cart_remove_product, thanks_page,
    signup_view, signin_view, signout_view, order_history, view_order, search
)

app_name = 'store'

urlpatterns = [
    path('', home, name='home'),
    path('category/<slug:category_slug>', home, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>', product_page, name='product_detail'),
    path('cart/', cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', add_cart, name='add_cart'),
    path('cart/remove/<int:product_id>', cart_remove, name='cart_remove'),
    path('cart/remove-product/<int:product_id>', cart_remove_product, name='cart_remove_product'),
    path('thank-you/<int:order_id>', thanks_page, name='thanks_page'),
    path('account/create/', signup_view, name='signup'),
    path('account/signin/', signin_view, name='signin'),
    path('acount/signout/', signout_view, name='signout'),
    path('order-history/', order_history, name='order_history'),
    path('order/<int:order_id>/', view_order, name='order_detail'),
    path('search/', search, name='search')
]

store/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=350, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:products_by_category', args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=350, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.category.slug, self.slug])


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'cart'
        ordering = ['date_added']
        verbose_name = 'Cart'
        verbose_name_plural = 'Cart'

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'cart_item'
        verbose_name = 'Cart Item'
        verbose_name_plural = 'Cart Items'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product


class Order(models.Model):
    token = models.CharField(max_length=250, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='USD Order Total')
    email_address = models.EmailField(max_length=250, blank=True, verbose_name='Email Address')
    created = models.DateTimeField(auto_now_add=True)
    billing_name = models.CharField(max_length=250, blank=True)
    billing_address1 = models.CharField(max_length=250, blank=True)
    billing_city = models.CharField(max_length=250, blank=True)
    billing_postcode = models.CharField(max_length=250, blank=True)
    billing_country = models.CharField(max_length=250, blank=True)
    shipping_name = models.CharField(max_length=250, blank=True)
    shipping_address1 = models.CharField(max_length=250, blank=True)
    shipping_city = models.CharField(max_length=250, blank=True)
    shipping_postcode = models.CharField(max_length=250, blank=True)
    shipping_country = models.CharField(max_length=250, blank=True)

    class Meta:
        db_table = 'order'
        ordering = ['-created']
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return str(self.id)


class OrderItem(models.Model):
    product = models.CharField(max_length=250)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='USD Price')
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    class Meta:
        db_table = 'order_item'
        verbose_name = 'Order Item'
        verbose_name_plural = 'Order Items'

    def sub_total(self):
        return self.quantity * self.price

    def __str__(self):
        return self.product


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)

    class Meta:
        db_table = 'review'
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'

    def __str__(self):
        return self.content

store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=250, help_text='eg. youremail@gmail.com')

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email', 'username', 'password1', 'password2'
        )

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from django.contrib.auth.models import Group, User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required

import stripe

from .models import Category, Product, Cart, CartItem, Order, OrderItem, Review
from .forms import SignUpForm


def home(request, category_slug=None):
    category_page = None
    # products = None

    if category_slug is not None:
        category_page = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category_page, available=True)
    else:
        products = Product.objects.all().filter(available=True)

    return render(request, 'store/home.html', {'category': category_page, 'products': products})


def product_page(request, category_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=category_slug, slug=product_slug)
    except Exception as e:
        raise e

    if request.method == 'POST' and request.user.is_authenticated and request.POST['content']:
        Review.objects.create(product=product, user=request.user, content=request.POST['content'])

    reviews = Review.objects.filter(product=product)

    return render(request, 'store/product.html', {'product': product, 'reviews': reviews})


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product, cart=cart, quantity=1
        )
        cart_item.save()
    return redirect('store:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    stripe.api_key = settings.STRIPE_SECRET_KEY
    stripe_total = int(total * 100)
    description = 'G-Store - New Order'
    data_key = settings.STRIPE_PUBLISHABLE_KEY

    if request.method == 'POST':
        try:
            token = request.POST['stripeToken']
            email = request.POST['stripeEmail']
            billing_name = request.POST['stripeBillingName']
            billing_address1 = request.POST['stripeBillingAddressLine1']
            billing_city = request.POST['stripeBillingAddressCity']
            billing_postcode = request.POST['stripeBillingAddressZip']
            billing_country = request.POST['stripeBillingAddressCountryCode']
            shipping_name = request.POST['stripeShippingName']
            shipping_address1 = request.POST['stripeShippingAddressLine1']
            shipping_city = request.POST['stripeShippingAddressCity']
            shipping_postcode = request.POST['stripeShippingAddressZip']
            shipping_country = request.POST['stripeShippingAddressCountryCode']
            customer = stripe.Customer.create(
                email=email,
                source=token
            )
            stripe.Charge.create(
                amount=stripe_total,
                currency='usd',
                description=description,
                customer=customer.id
            )
            order_details = Order.objects.create(
                token=token,
                total=total,
                email_address=email,
                billing_name=billing_name,
                billing_address1=billing_address1,
                billing_city=billing_city,
                billing_postcode=billing_postcode,
                billing_country=billing_country,
                shipping_name=shipping_name,
                shipping_address1=shipping_address1,
                shipping_city=shipping_city,
                shipping_postcode=shipping_postcode,
                shipping_country=shipping_country
            )
            order_details.save()

            for order_item in cart_items:
                OrderItem.objects.create(
                    product=order_item.product.name,
                    quantity=order_item.quantity,
                    price=order_item.product.price,
                    order=order_details
                )
                products = Product.objects.get(pk=order_item.product.pk)
                products.stock = int(order_item.product.stock - order_item.quantity)
                products.save()
                order_item.delete()

                print('the order has been created')
            return redirect('store:thanks_page', order_details.pk)

        except Exception as e:
            return False, e

    context = {
        'cart_items': cart_items,
        'total': total,
        'counter': counter,
        'data_key': data_key,
        'stripe_total': stripe_total,
        'description': description
    }
    return render(request, 'store/cart.html', context)


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(cart=cart, product=product)

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('store:cart_detail')


def cart_remove_product(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(cart=cart, product=product)
    cart_item.delete()
    return redirect('store:cart_detail')


def thanks_page(request, order_id):
    if order_id:
        customer_order = get_object_or_404(Order, pk=order_id)
    return render(request, 'store/thank_you.html', {'customer_order': customer_order})


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            form.save()
            signup_user = User.objects.get(username=username)
            customer_group = Group.objects.get(name='Customer')
            customer_group.user_set.add(signup_user)
    else:
        form = SignUpForm()
    return render(request, 'store/signup.html', {'form': form})


def signin_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('store:home')
            else:
                return redirect('store:signup')
    else:
        form = AuthenticationForm()
    return render(request, 'store/signin.html', {'form': form})


def signout_view(requets):
    logout(requets)
    return redirect('store:signin')


@login_required(redirect_field_name='next', login_url='store:signin')
def order_history(request):
    email = request.user.email
    order_details = Order.objects.filter(email_address=email)
    return render(request, 'store/orders_list.html', {'order_details': order_details})


@login_required(redirect_field_name='next', login_url='store:signin')
def view_order(request, order_id):
    email = request.user.email
    order = Order.objects.get(pk=order_id, email_address=email)
    order_items = OrderItem.objects.filter(order=order)
    return render(request, 'store/order_detail.html', {'order': order, 'order_items': order_items})


def search(request):
    products = Product.objects.filter(name__contains=request.GET['search'])
    return render(request, 'store/home.html', {'products': products})

store/templates/store/cart.html
{% extends 'base.html' %}
{% block title %} Cart {% endblock title %}

{% block content %}
    <section id="cart">
        {% if not cart_items %}
            <div class="text-center">
                <br>
                <h1 class="text-center product-title">Your shopping cart is empty</h1>
                <p class="text-center">
                    Please click <a href="{% url 'store:home' %}">here</a> to continue shopping.
                </p>
            </div>
        {% else %}
            <div class="text-center">
                <br>
                <div class="text-center product_title">
                    You shopping cart
                </div>
            </div>
            <div class="row mx-auto">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table cart_table">
                        <thead class="cart_thead">
                        <tr>
                            <th colspan="4">
                                Your items
                            </th>
                        </tr>
                        </thead>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="{{ cart_item.product.get_absolute_url }}">
                                        <img src="{{ cart_item.product.image.url }}" width="100" height="100"
                                             alt="">
                                    </a>
                                </td>
                                <td class="text-left">
                                    {{ cart_item.product.name }}
                                    <br>
                                    SKU: {{ cart_item.product.id }}
                                    <br>
                                    Unit Price: ${{ cart_item.product.price }}
                                    <br>
                                    Qty: {{ cart_item.quantity }} x ${{ cart_item.product.price }}
                                </td>
                                <td>
                                    ${{ cart_item.sub_total }}
                                </td>
                                <td>
                                    {% if cart_item.quantity < cart_item.product.stock %}
                                        &nbsp;<a href="{% url 'store:add_cart' cart_item.product.id %}"
                                                 class="text-decoration-none">
                                        <i class="fas fa-plus-circle cart_icon"></i>
                                    </a>
                                        &nbsp;<a href="{% url 'store:cart_remove' cart_item.product.id %}"
                                                 class="text-decoration-none">
                                        <i class="fas fa-minus-circle cart_icon"></i>
                                    </a>
                                        &nbsp;<a href="{% url 'store:cart_remove_product' cart_item.product.id %}"
                                                 class="text-decoration-none">
                                        <i class="fas fa-trash-alt cart_icon"></i>
                                    </a>
                                    {% else %}
                                        &nbsp;<a href="{% url 'store:cart_remove' cart_item.product.id %}"
                                                 class="text-decoration-none">
                                        <i class="fas fa-minus-circle cart_icon"></i>
                                    </a>
                                        &nbsp;<a href="{% url 'store:cart_remove_product' cart_item.product.id %}"
                                                 class="text-decoration-none">
                                        <i class="fas fa-trash-alt cart_icon"></i>
                                    </a>
                                    {% endif %}

                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table cart_table">
                        <thead class="cart_thead">
                        <tr>
                            <th>Check Out</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                Please review you cart items before proceeding with the payment.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                Your total is: <strong>${{ total }}</strong>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="mx-auto">
                        <form action="" method="post">
                            {% csrf_token %}
                            <script src="https://checkout.stripe.com/checkout.js"
                                    class="stripe-button"
                                    data-key="{{ data_key }}"
                                    data-amount="{{ stripe_total }}"
                                    data-name="G-Store"
                                    data-description="{{ description }}"
                                    data-locale="auto"
                                    data-currency="usd"
                                    data-shipping-address="true"
                                    data-billing-address="true"
                                    data-zip-code="true"
                            >
                            </script>
                            {#                            <script src="https://js.stripe.com/v3/"></script>#}
                            {#                            <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>#}
                        </form>
                        <a href="{% url 'store:home' %}" style="text-decoration: none;">
                            <button type="button" class="btn btn-lg btn-block bg-dark text-white">
                                Continue Shopping
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        {% endif %}
    </section>
{% endblock content %}

store/templates/store/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock title %}

{% block content %}
    <section id="homepage">
        <div class="container-fluid">
            <div class="row">
                <img style="width: 100%;" src="{% static 'img/image.jpg' %}" alt="">
            </div>
        </div>

        <div class="py-4">
            <div class="container">
                <div class="row">
                    <div class="col-10 mx-auto my-2 text-center">
                        <h1 class="text-capitalize font-weight-bold">
                            All Products
                        </h1>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                {% for product in products %}
                    <div class="col-9 mx-auto col-md-6 col-lg-3">
                        <div class="card mb-4" style="border-color: transparent;">
                            <div class="p-4">
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
                                </a>
                            </div>
                            <div class="card-footer d-flex justify-content-between"
                                 style="background: transparent; border-color: transparent;">
                                <p class="font-weight-bold mb-0">
                                    {{ product.name }}
                                </p>
                                <h5 class="text-info font-italic mb-0">
                                    <span class="mr-1">$</span>{{ product.price }}
                                </h5>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock content %}

store/templates/store/order_detail.html
{% extends 'base.html' %}
{% block title %} Order Details {% endblock title %}

{% block content %}
    <section id="order-detail">
        <div class="container">
            <div class="text-center">
                <br>
                <h1 class="text-center product_title">Order Details</h1>
                <br>
                <table class="table table-bordered">
                    <tr>
                        <td class="text-left" colspan="2">
                            <b>Order: </b>#{{ order.id }} <br>
                            <b>Date: </b>{{ order.created|date:'d M Y' }} <br>
                            <b>Order Total: </b>${{ order.total }} <br>
                            <b>Order Status: </b><i class="fas fa-check"></i> Complete <br>
                        </td>
                        <td class="text-left" colspan="2">
                            <b>Billing Address: </b><br>
                            {{ order.billing_name }} <br>
                            {{ order.billing_address1 }} <br>
                            {{ order.billing_city }} <br>
                            {{ order.billing_postcode }} <br>
                            {{ order.billing_country }} <br>
                        </td>
                    </tr>
                    <tr>
                        <td><b>Product Description</b></td>
                        <td><b>Qty</b></td>
                        <td><b>Unit Price</b></td>
                        <td><b>Sub-Total</b></td>
                    </tr>
                    {% for item in order_items %}
                        <tr>
                            <td>{{ item.product }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>${{ item.price }}</td>
                            <td>${{ item.sub_total }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="3" class="text-right"><b>Total</b></td>
                        <td>${{ order.total }}</td>
                    </tr>
                    <tr>
                        <td colspan="3" class="text-right"><b>Total Paid</b></td>
                        <td>${{ order.total }}</td>
                    </tr>
                    <tr>
                        <td class="text-left" colspan="2">
                            <b>Shipping Address: </b><br>
                            {{ order.shipping_name }} <br>
                            {{ order.billing_address1 }} <br>
                            {{ order.billing_city }} <br>
                            {{ order.billing_postcode }} <br>
                            {{ order.billing_country }} <br>
                        </td>
                        <td class="text-left" colspan="2">
                            <b>Payment Details: </b> <br>
                            The order #{{ order.id }} has been paid successfully.
                        </td>
                    </tr>
                </table>
                <button class="btn btn-secondary" onclick="window.print();">
                    <i class="fas fa-print"></i> Print Order
                </button>
            </div>
        </div>
        <br><br>
    </section>
{% endblock content %}

store/templates/store/orders_list.html
{% extends 'base.html' %}
{% block title %} Order History {% endblock title %}

{% block content %}
    <section id="order-history">
        <div class="text-center">
            <br>
            <h1 class="text-center product_title">Order History</h1>
            <br>
            {% if order_details %}
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Order Number</th>
                        <th>Order Date</th>
                        <th>Total Amount</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in order_details %}
                        <tr>
                            <td>{{ order.id }}</td>
                            <td>{{ order.created|date:'d M Y' }}</td>
                            <td>{{ order.total }}</td>
                            <td><i class="fas fa-check"></i>&nbsp;Complete</td>
                            <td><a href="{% url 'store:order_detail' order.id %}">View Order</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>
                    You have not placed any order.
                    <br><br>
                    <a href="{% url 'store:home' %}" class="btn btn-secondary">Continue shopping</a>
                </p>
            {% endif %}
        </div>
        <br><br>
    </section>
{% endblock content %}

store/templates/store/product.html
{% extends 'base.html' %}
{% block title %} Product {% endblock title %}

{% block content %}
    <section id="product">
        <div class="container py-5">
            <div class="row mt-5">
                <div class="col-10 mx-auto col-md-3 my-3">
                    <img src="{{ product.image.url }}" alt="">
                </div>
                <div class="col-10 mx-auto col-md-3 my-3">
                    <div>
                        <h1 class="product_title">{{ product.name }}</h1>
                        <h5 class="text-info font-italic mb-3">
                            <span class="mr-1">$</span>{{ product.price }}
                        </h5>
                        <p class="product_description">Product Description</p>
                        <p class="text-justify product_text">
                            {{ product.description }}
                        </p>
                        {% if product.stock <= 0 %}
                            <p class="text-justify product_text">
                                <b>Out of Stock</b>
                            </p>
                        {% else %}
                            <a href="{% url 'store:add_cart' product.id %}" class="btn btn-secondary">Add to Cart</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header"><h4>Reviews</h4></div>
                {% if user.is_authenticated %}
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="content" hidden></label>
                                <textarea name="content" id="content" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Post</button>
                            </div>
                        </form>
                    </div>
                {% endif %}

                {% if reviews.count > 0 %}
                    <ul class="list-group list-group-flush">
                        {% for review in reviews %}
                            <li class="list-group-item">
                                <h5>{{ review.user.username }}</h5>
                                <p class="card-text">{{ review.content }}</p>
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock content %}