core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import (
    home, product_page, add_cart, cart_detail, cart_remove, cart_remove_product, thanks_page,
    signup_view, signin_view, signout_view, order_history, view_order, search
)

app_name = 'store'

urlpatterns = [
    path('', home, name='home'),
    path('category/<slug:category_slug>', home, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>', product_page, name='product_detail'),
    path('cart/', cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', add_cart, name='add_cart'),
    path('cart/remove/<int:product_id>', cart_remove, name='cart_remove'),
    path('cart/remove-product/<int:product_id>', cart_remove_product, name='cart_remove_product'),
    path('thank-you/<int:order_id>', thanks_page, name='thanks_page'),
    path('account/create/', signup_view, name='signup'),
    path('account/signin/', signin_view, name='signin'),
    path('acount/signout/', signout_view, name='signout'),
    path('order-history/', order_history, name='order_history'),
    path('order/<int:order_id>/', view_order, name='order_detail'),
    path('search/', search, name='search')
]

store/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=350, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:products_by_category', args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=350, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.category.slug, self.slug])


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'cart'
        ordering = ['date_added']
        verbose_name = 'Cart'
        verbose_name_plural = 'Cart'

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'cart_item'
        verbose_name = 'Cart Item'
        verbose_name_plural = 'Cart Items'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product


class Order(models.Model):
    token = models.CharField(max_length=250, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='USD Order Total')
    email_address = models.EmailField(max_length=250, blank=True, verbose_name='Email Address')
    created = models.DateTimeField(auto_now_add=True)
    billing_name = models.CharField(max_length=250, blank=True)
    billing_address1 = models.CharField(max_length=250, blank=True)
    billing_city = models.CharField(max_length=250, blank=True)
    billing_postcode = models.CharField(max_length=250, blank=True)
    billing_country = models.CharField(max_length=250, blank=True)
    shipping_name = models.CharField(max_length=250, blank=True)
    shipping_address1 = models.CharField(max_length=250, blank=True)
    shipping_city = models.CharField(max_length=250, blank=True)
    shipping_postcode = models.CharField(max_length=250, blank=True)
    shipping_country = models.CharField(max_length=250, blank=True)

    class Meta:
        db_table = 'order'
        ordering = ['-created']
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return str(self.id)


class OrderItem(models.Model):
    product = models.CharField(max_length=250)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='USD Price')
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    class Meta:
        db_table = 'order_item'
        verbose_name = 'Order Item'
        verbose_name_plural = 'Order Items'

    def sub_total(self):
        return self.quantity * self.price

    def __str__(self):
        return self.product


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)

    class Meta:
        db_table = 'review'
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'

    def __str__(self):
        return self.content

store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=250, help_text='eg. youremail@gmail.com')

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email', 'username', 'password1', 'password2'
        )

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from django.contrib.auth.models import Group, User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required

import stripe

from .models import Category, Product, Cart, CartItem, Order, OrderItem, Review
from .forms import SignUpForm


def home(request, category_slug=None):
    category_page = None
    # products = None

    if category_slug is not None:
        category_page = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category_page, available=True)
    else:
        products = Product.objects.all().filter(available=True)

    return render(request, 'store/home.html', {'category': category_page, 'products': products})


def product_page(request, category_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=category_slug, slug=product_slug)
    except Exception as e:
        raise e

    if request.method == 'POST' and request.user.is_authenticated and request.POST['content']:
        Review.objects.create(product=product, user=request.user, content=request.POST['content'])

    reviews = Review.objects.filter(product=product)

    return render(request, 'store/product.html', {'product': product, 'reviews': reviews})


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product, cart=cart, quantity=1
        )
        cart_item.save()
    return redirect('store:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    stripe.api_key = settings.STRIPE_SECRET_KEY
    stripe_total = int(total * 100)
    description = 'G-Store - New Order'
    data_key = settings.STRIPE_PUBLISHABLE_KEY

    if request.method == 'POST':
        try:
            token = request.POST['stripeToken']
            email = request.POST['stripeEmail']
            billing_name = request.POST['stripeBillingName']
            billing_address1 = request.POST['stripeBillingAddressLine1']
            billing_city = request.POST['stripeBillingAddressCity']
            billing_postcode = request.POST['stripeBillingAddressZip']
            billing_country = request.POST['stripeBillingAddressCountryCode']
            shipping_name = request.POST['stripeShippingName']
            shipping_address1 = request.POST['stripeShippingAddressLine1']
            shipping_city = request.POST['stripeShippingAddressCity']
            shipping_postcode = request.POST['stripeShippingAddressZip']
            shipping_country = request.POST['stripeShippingAddressCountryCode']
            customer = stripe.Customer.create(
                email=email,
                source=token
            )
            stripe.Charge.create(
                amount=stripe_total,
                currency='usd',
                description=description,
                customer=customer.id
            )
            order_details = Order.objects.create(
                token=token,
                total=total,
                email_address=email,
                billing_name=billing_name,
                billing_address1=billing_address1,
                billing_city=billing_city,
                billing_postcode=billing_postcode,
                billing_country=billing_country,
                shipping_name=shipping_name,
                shipping_address1=shipping_address1,
                shipping_city=shipping_city,
                shipping_postcode=shipping_postcode,
                shipping_country=shipping_country
            )
            order_details.save()

            for order_item in cart_items:
                OrderItem.objects.create(
                    product=order_item.product.name,
                    quantity=order_item.quantity,
                    price=order_item.product.price,
                    order=order_details
                )
                products = Product.objects.get(pk=order_item.product.pk)
                products.stock = int(order_item.product.stock - order_item.quantity)
                products.save()
                order_item.delete()

                print('the order has been created')
            return redirect('store:thanks_page', order_details.pk)

        except Exception as e:
            return False, e

    context = {
        'cart_items': cart_items,
        'total': total,
        'counter': counter,
        'data_key': data_key,
        'stripe_total': stripe_total,
        'description': description
    }
    return render(request, 'store/cart.html', context)


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(cart=cart, product=product)

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('store:cart_detail')


def cart_remove_product(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(cart=cart, product=product)
    cart_item.delete()
    return redirect('store:cart_detail')


def thanks_page(request, order_id):
    if order_id:
        customer_order = get_object_or_404(Order, pk=order_id)
    return render(request, 'store/thank_you.html', {'customer_order': customer_order})


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            form.save()
            signup_user = User.objects.get(username=username)
            customer_group = Group.objects.get(name='Customer')
            customer_group.user_set.add(signup_user)
    else:
        form = SignUpForm()
    return render(request, 'store/signup.html', {'form': form})


def signin_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('store:home')
            else:
                return redirect('store:signup')
    else:
        form = AuthenticationForm()
    return render(request, 'store/signin.html', {'form': form})


def signout_view(requets):
    logout(requets)
    return redirect('store:signin')


@login_required(redirect_field_name='next', login_url='store:signin')
def order_history(request):
    email = request.user.email
    order_details = Order.objects.filter(email_address=email)
    return render(request, 'store/orders_list.html', {'order_details': order_details})


@login_required(redirect_field_name='next', login_url='store:signin')
def view_order(request, order_id):
    email = request.user.email
    order = Order.objects.get(pk=order_id, email_address=email)
    order_items = OrderItem.objects.filter(order=order)
    return render(request, 'store/order_detail.html', {'order': order, 'order_items': order_items})


def search(request):
    products = Product.objects.filter(name__contains=request.GET['search'])
    return render(request, 'store/home.html', {'products': products})

store/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <title>{% block title %} {% endblock title %}</title>
</head>
<body>

{% include 'navbar.html' %}

{% block content %} {% endblock content %}

{% include 'footer.html' %}

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/all.min.js' %}"></script>
</body>
</html>

store/templates/footer.html
<footer class="bg-dark text-light p-3 mt-5">
    <div class="container">
        <p class="lead text-center">
            Copyright &copy; {% now 'Y' %}
        </p>
    </div>
</footer>

store/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-dark">
    <a href="{% url 'store:home' %}" class="navbar-brand"><i class="fas fa-store text-warning fa-2x"></i></a>
    <button type="button" class="navbar-toggler bg-light" data-toggle="collapse" data-target="#nav">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="nav">
        <ul class="navbar-nav">
            <li class="navbar-item dropdown">
                <a class="nav-link text-light text-uppercase font-weight-bold px-3 dropdown-toggle" href=""
                   data-toggle="dropdown">
                    Categories
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'store:home' %}">All Products</a>
                    {% for category in links %}
                        <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </li>
            <li class="navbar-item">
                <a class="nav-link text-light text-uppercase font-weight-bold px-3" href="">
                    Contact
                </a>
            </li>
            <li class="navbar-item">
                <a class="nav-link text-light text-uppercase font-weight-bold px-3" href="">
                    About
                </a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="navbar-item dropdown navbar-link-item">
                <span class="nav-link text-light text-uppercase font-weight-bold px-3 dropdown-toggle"
                      data-toggle="dropdown">
                    Welcome, {{ request.user }} <i class="fa fa-user-circle"></i>
                </span>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'store:order_history' %}">Order History</a>
                    </div>
                </li>
                <li class="navbar-item">
                    <a class="nav-link text-light text-uppercase font-weight-bold px-3"
                       href="{% url 'store:signout' %}">
                        Signout <i class="fa fa-sign-out-alt"></i>
                    </a>
                </li>
            {% else %}
                <li class="navbar-item">
                    <a class="nav-link text-light text-uppercase font-weight-bold px-3" href="{% url 'store:signup' %}">
                        Sign Up <i class="fa fa-user-plus"></i>
                    </a>
                </li>
                <li class="navbar-item">
                    <a class="nav-link text-light text-uppercase font-weight-bold px-3" href="{% url 'store:signin' %}">
                        Sign In <i class="fa fa-sign-in-alt"></i>
                    </a>
                </li>
            {% endif %}
            {% if item_count > 0 %}
                <li class="navbar-item">
                <a class="nav-link text-light text-uppercase font-weight-bold px-3"
                   href="{% url 'store:cart_detail' %}">
                    <i class="fas fa-shopping-cart"></i>({{ item_count }})
                </a>
            {% endif %}
        </ul>

        <form class="form-inline" action="{% url 'store:search' %}" method="get">
            <div class="input-group px-3">
                <label for="search" hidden></label>
                {% if values.search %}
                    <input type="text" name="search" id="search" placeholder="Search" class="form-control"
                           value="{{ values.search }}">
                {% else %}
                    <input type="text" name="search" id="search" placeholder="Search" class="form-control">
                {% endif %}
                <div class="input-group-append">
                    <button type="submit" class="btn btn-warning"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
    </div>
</nav>